// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check():Promise<boolean>;

export function Loggedin():Promise<boolean>;

export function Login(arg1:string):Promise<boolean>;
