// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['main']['App']['Check']();
}

export function Loggedin() {
  return window['go']['main']['App']['Loggedin']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}
